build:
	hla -p:tmp 	10_01ctlHW.hla
	hla -p:tmp 	10_02ctWhile.hla
	hla -p:tmp 	10_03ctWhile2.hla
	hla -p:tmp 	10_04putiDemo.hla
	hla -p:tmp 	10_05put32Demo.hla
	hla -p:tmp 	10_06puti32Demo.hla
	hla -p:tmp 	10_07demoSines.hla
	hla -p:tmp 	10_08demoCase.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
