build:
	hla -p:tmp 	9_01TestMul64.hla
	hla -p:tmp 	9_02testDiv128.hla
	hla -p:tmp 	9_03testDiv128b.hla
	hla -p:tmp 	9_04out128.hla
	hla -p:tmp 	9_05xin128.hla
	hla -p:tmp 	9_06uin128.hla
	hla -p:tmp 	9_07MixedArith.hla
	hla -p:tmp 	9_08genSines.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
