build:
	hla -p:tmp 	8_01SimpleFileOutput.hla
	hla -p:tmp 	8_02SimpleFileInput.hla
	hla -p:tmp 	8_03SimpleFileInput2.hla
	hla -p:tmp 	8_04AppendDemo.hla
	hla -p:tmp 	8_05EolnDemo.hla
	hla -p:tmp 	8_06RandomAccessDemo.hla
	hla -p:tmp 	8_07TruncateDemo.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
