build:
	hla -p:tmp 	7_01labelDemo.hla
	hla -p:tmp 	7_02labelArrays.hla
	hla -p:tmp 	7_03regIndJmp.hla
	hla -p:tmp 	7_04memIndJmp.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
