build:
	hla -p:tmp 	1_01HelloWorld.hla
	hla -p:tmp 	1_02DemoVars.hla
	hla -p:tmp 	1_03DemoMOVaddSUB.hla
	hla -p:tmp 	1_04NumsInColumns.hla
	hla -p:tmp 	1_05NumsInColumns2.hla
	hla -p:tmp 	1_06charInput.hla
	hla -p:tmp 	1_07intInput.hla
	hla -p:tmp 	1_08TestBadInput.hla
	hla -p:tmp 	1_09TestBadInput2.hla
	hla -p:tmp 	1_10TestBadInput4.hla
	hla -p:tmp 	1_11TestBadInput5.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
