build:
	hla -p:tmp 	4_01BoundDemo.hla
	hla -p:tmp 	4_02INTOdemo.hla
	hla -p:tmp 	4_03ConstDemo.hla
	hla -p:tmp 	4_04VALdemo.hla
	hla -p:tmp 	4_05PtrConstDemo.hla
	hla -p:tmp 	4_06UninitPtrDemo.hla
	hla -p:tmp 	4_07BadTypePtrDemo.hla
	hla -p:tmp 	4_08StrDemo.hla
	hla -p:tmp 	4_09LenMaxlenDemo.hla
	hla -p:tmp 	4_10strallocDemo.hla
	hla -p:tmp 	4_11strfreeDemo.hla
	hla -p:tmp 	4_12strfreeDemo2.hla
	hla -p:tmp 	4_13strRefAssignDemo.hla
	hla -p:tmp 	4_14strcpyDemo.hla
	hla -p:tmp 	4_15stra_cpyDemo.hla
	hla -p:tmp 	4_16strcatDemo.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
