//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.269
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintPreview.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmSearchResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmSearchResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintPreview.Resources.FrmSearchResources", typeof(FrmSearchResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find.
        /// </summary>
        internal static string Button1 {
            get {
                return ResourceManager.GetString("Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        internal static string Button2 {
            get {
                return ResourceManager.GetString("Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canteen.
        /// </summary>
        internal static string CheckBox1 {
            get {
                return ResourceManager.GetString("CheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Solidarity pony.
        /// </summary>
        internal static string CheckBox10 {
            get {
                return ResourceManager.GetString("CheckBox10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ATM work.
        /// </summary>
        internal static string CheckBox11 {
            get {
                return ResourceManager.GetString("CheckBox11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dormitory.
        /// </summary>
        internal static string CheckBox12 {
            get {
                return ResourceManager.GetString("CheckBox12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mobile Unit.
        /// </summary>
        internal static string CheckBox13 {
            get {
                return ResourceManager.GetString("CheckBox13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Smaller communities.
        /// </summary>
        internal static string CheckBox14 {
            get {
                return ResourceManager.GetString("CheckBox14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Training.
        /// </summary>
        internal static string CheckBox15 {
            get {
                return ResourceManager.GetString("CheckBox15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drafting.
        /// </summary>
        internal static string CheckBox16 {
            get {
                return ResourceManager.GetString("CheckBox16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian school.
        /// </summary>
        internal static string CheckBox2 {
            get {
                return ResourceManager.GetString("CheckBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Membership.
        /// </summary>
        internal static string CheckBox3 {
            get {
                return ResourceManager.GetString("CheckBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Legal desk.
        /// </summary>
        internal static string CheckBox4 {
            get {
                return ResourceManager.GetString("CheckBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Showers.
        /// </summary>
        internal static string CheckBox5 {
            get {
                return ResourceManager.GetString("CheckBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Centre for Aid.
        /// </summary>
        internal static string CheckBox6 {
            get {
                return ResourceManager.GetString("CheckBox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Secretariat volunteers.
        /// </summary>
        internal static string CheckBox7 {
            get {
                return ResourceManager.GetString("CheckBox7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wardrobe.
        /// </summary>
        internal static string CheckBox8 {
            get {
                return ResourceManager.GetString("CheckBox8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Listening center.
        /// </summary>
        internal static string CheckBox9 {
            get {
                return ResourceManager.GetString("CheckBox9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In service.
        /// </summary>
        internal static string RadioButton1 {
            get {
                return ResourceManager.GetString("RadioButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Supporter.
        /// </summary>
        internal static string RadioButton2 {
            get {
                return ResourceManager.GetString("RadioButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pending.
        /// </summary>
        internal static string RadioButton3 {
            get {
                return ResourceManager.GetString("RadioButton3", resourceCulture);
            }
        }
    }
}
