//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.269
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintPreview.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageEn() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintPreview.Resources.MessageEn", typeof(MessageEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert a number page..
        /// </summary>
        internal static string PreviewDialogGotoTextBox_TextChanged {
            get {
                return ResourceManager.GetString("PreviewDialogGotoTextBox_TextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attention, the textbox from and to must be numeric..
        /// </summary>
        internal static string PreviewDialogPrintButton_Click {
            get {
                return ResourceManager.GetString("PreviewDialogPrintButton_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attention, the initial page must be minor of last page..
        /// </summary>
        internal static string PreviewDialogPrintButton_Click_1 {
            get {
                return ResourceManager.GetString("PreviewDialogPrintButton_Click_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select at least one category among the top 3 and one or more tasks..
        /// </summary>
        internal static string ValidationsChechBoxAndRadioButtonChecked {
            get {
                return ResourceManager.GetString("ValidationsChechBoxAndRadioButtonChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string ValidationsChechFileExist {
            get {
                return ResourceManager.GetString("ValidationsChechFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a not found..
        /// </summary>
        internal static string ValidationsChechFileExist1 {
            get {
                return ResourceManager.GetString("ValidationsChechFileExist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There are empty fields , fill in the fields in all its parts!.
        /// </summary>
        internal static string ValidationsCheckTextBoxEmpty {
            get {
                return ResourceManager.GetString("ValidationsCheckTextBoxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There are empty fields , fill in the fields in all its parts!.
        /// </summary>
        internal static string ValidationsCheckTextBoxForDelete {
            get {
                return ResourceManager.GetString("ValidationsCheckTextBoxForDelete", resourceCulture);
            }
        }
    }
}
