build:
	hla -p:tmp 	5_01zeroBytesDemo.hla
	hla -p:tmp 	5_02nonWorkingProgram.hla
	hla -p:tmp 	5_03callerPreservation.hla
	hla -p:tmp 	5_04callerPreservation2.hla
	hla -p:tmp 	5_05demoGlobalScope.hla
	hla -p:tmp 	5_06demoLocalVar.hla
	hla -p:tmp 	5_07demoLocalVars2.hla
	hla -p:tmp 	5_08PassByRefDemo.hla
	hla -p:tmp 	5_09qsDemo.hla
	hla -p:tmp 	5_10missingRET.hla
	hla -p:tmp 	5_11extraPOP.hla
	hla -p:tmp 	5_12printDemo.hla
	hla -p:tmp 	5_13AccValueParm.hla
	hla -p:tmp 	5_14manValueParms.hla
	hla -p:tmp 	5_15PassingExpr.hla
	hla -p:tmp 	5_16AccRefParm.hla
	hla -p:tmp 	5_17AccRefArray.hla
	hla -p:tmp 	5_21MAIN2.HLA 5_22UNIT2.HLA

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
