examples:

	cd ch01
	make
	cd ..

	cd ch02
	make
	cd ..

	cd ch03
	make
	cd ..

	cd ch04
	make
	cd ..

	cd ch05
	make
	cd ..

	cd ch07
	make
	cd ..

	cd ch08
	make
	cd ..

	cd ch09
	make
	cd ..

	cd ch10
	make
	cd ..

	cd ch13
	make
	cd ..




clean:
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link

	cd ch01
	make clean
	cd ..

	cd ch02
	make clean
	cd ..

	cd ch03
	make clean
	cd ..

	cd ch04
	make clean
	cd ..

	cd ch05
	make clean
	cd ..

	cd ch07
	make clean
	cd ..

	cd ch08
	make clean
	cd ..

	cd ch09
	make clean
	cd ..

	cd ch10
	make clean
	cd ..

	cd ch13
	make clean
	cd ..
















	 
