build:
	hla -p:tmp 	2_01ConvertToHex.hla
	hla -p:tmp 	2_02ConvertToDecimal.hla
	hla -p:tmp 	2_03ConvertToDecimal2.hla
	hla -p:tmp 	2_04HexIO.hla
	hla -p:tmp 	2_05LogicalOp.hla
	hla -p:tmp 	2_06twosComplement.hla
	hla -p:tmp 	2_07UnsExample.hla
	hla -p:tmp 	2_08signExtension.hla
	hla -p:tmp 	2_09dateDemo.hla
	hla -p:tmp 	2_11charInputDemo.hla
	hla -p:tmp 	2_12charInputDemo2.hla
	hla -p:tmp 	eolnDemo2.hla

clean:
	delete *.exe
	delete *.obj
	delete *.asm
	delete *.bak
	delete *.link
	delete *.inc
	delete tmp\*
















	 
